### ISSUE TITLE
3d model rotation

### ISSUE THREAD

**Issue by Betaboycreatorgithub** [bananaturtlesandwich/stove#11]
for some reason, all the models in stove look weirdly rotated, making it super hard to use for map editing. Heres an example:
![problemthingy](https://github.com/bananaturtlesandwich/stove/assets/116523251/ca8571a6-59ca-4372-8a5c-46f078faf58e)

Is there a potential fix for this?

**Comment by Betaboycreatorgithub** [comment]
note: its an oodle pack

**Comment by bananaturtlesandwich** [comment]
Hmm I've never encountered this :/

**Comment by bananaturtlesandwich** [comment]
It shouldn't be an issue with the pak type

**Comment by bananaturtlesandwich** [comment]
I may be converting the rotations badly which would be only evident on more complex rotations so could be it

**Comment by Betaboycreatorgithub** [comment]
alr just lmk if you figure out a possible fix!

**Comment by bananaturtlesandwich** [comment]
i think I fixed rotation in the latest release actually give it a try

**Comment by bananaturtlesandwich** [comment]
also gonna have to close for inactivity if you don't respond
