### ISSUE TITLE
UI Draw issue

### ISSUE THREAD

**Issue by Creaper1** [bananaturtlesandwich/stove#12]
UI only draws a portion of the screen. Very difficult to use.
![Screenshot 2024-01-15 102821](https://github.com/bananaturtlesandwich/stove/assets/50012844/463696b2-ffe4-4f8c-88fd-21a386336847)

**Comment by bananaturtlesandwich** [comment]
sorry this doesn't happen on my machine so i couldn't catch it - i am in the process of porting stove to a more stable backend in bevy so this should be fixed in 0.13

**Comment by bananaturtlesandwich** [comment]
@Creaper1 should be fixed on new update
