### ISSUE TITLE
Map doesn't load, uses all the RAM, then crashes.

### ISSUE THREAD

**Issue by Visual917** [bananaturtlesandwich/stove#14]
![image](https://github.com/bananaturtlesandwich/stove/assets/30579752/17990d8f-2e88-4e46-b62b-4e0397d16267)

The map won't load, use up all my RAM (why, instead of VRAM?) and then crashes without responding.

The game's PAK file is only 10 GB. It works without any meshes when I don't choose my pak folder but then I cannot mod the game because the map is basically just blank boxes. The program either needs one by one mesh visibility or like an area based layer system. I have 32 GBs of RAM.

**Comment by bananaturtlesandwich** [comment]
yikes - I'll have a look at ram usage for me later to see if I can replicate. It should be using a graphics card if that's available

**Comment by Visual917** [comment]
@bananaturtlesandwich open to assist over Discord. I do have a 3090.

**Comment by bananaturtlesandwich** [comment]
It's not going to be crashing loading the pak more likely due to loading the meshes  themselves - how high poly are the models?

**Comment by Visual917** [comment]
Not sure. The game is Drug Dealer Simulator

**Comment by bananaturtlesandwich** [comment]
Not gonna be available until tomorrow sorry but very much willing to debug with you

**Comment by Visual917** [comment]
@bananaturtlesandwich So how should we proceed?

**Comment by bananaturtlesandwich** [comment]
Sorry gonna be a couple of hours - I'll contact on discord when I'm free

**Comment by Visual917** [comment]
alright. my username is 0xYonga

**Comment by bananaturtlesandwich** [comment]
(notes for myself since we discussed it) okay i believe the issue here is wgpu runs out of storage in memory for texture data. i made the duct tape fix of having a setting to disable textures which allows the maps to load the stuff. in future to help with this maybe use asset servers?
