### ISSUE TITLE
Mesh loading error

### ISSUE THREAD

**Issue by PlushPersik** [bananaturtlesandwich/stove#15]
I'm trying to view the Hello Neighbor map with the name: "Main_Level.umap" but when I select the game engine version. And it seems it 4.20 (and i already tried it on both newer and older versions), warnings appear on the right that it was not possible to load the meshes. And there are pink cubes on the screen, these are most likely objects that do not have a mesh. What to do in this case?
![image](https://github.com/bananaturtlesandwich/stove/assets/70471344/a5f941c0-bc22-4ef1-8771-cc1fa13f0642)

File umap: https://www.mediafire.com/file/3os53uuj748lpc2/Main_Level.umap/file

I'm using windows 10 pro x64

**Comment by PlushPersik** [comment]
> what do you have you selected for your paks?

nothing, i'm just selected a umap file from game and all. Hello Neighbor release files is doesn
't paked.

**Comment by bananaturtlesandwich** [comment]
Ah I see right I should probably allow for loose loading of files shouldn't I

**Comment by PlushPersik** [comment]
idk

**Comment by PlushPersik** [comment]
ok i don't know how to fix this problem
