### ISSUE TITLE
Add .Utoc/.Ucas IOStore functionality?

### ISSUE THREAD

**Issue by Aeyth8** [bananaturtlesandwich/stove#16]
**0.13.1-alpha**

For my specific game, the .umaps are only stored within the .utoc. 
I extracted the .umap using FModel, but I get an error saying **"File is not a valid uasset file"**

I've had this issue before, so I know it's just FModel not extracting it properly or etc/something/something I have no clue about
I extracted the .umap from FModel using the raw data option (.uasset)
The other options do not work and export an empty nonexistent folder.

**Assets**
4.27.2 collectibleworld.umap, from said IOStore game, if I must provide more details on said game, it'll have to be more private for vital security reasons.

**Operating system**
Windows 10 Pro

**Additional context**
I dunno, I'm a wannabe dev who's trying to improve all the time.

**Comment by bananaturtlesandwich** [comment]
sorry for late reply but you should be able to use stove if you use zentools for ue4 (https://github.com/WistfulHopes/ZenTools-UE4) to extract the umaps and repack them this should work

**Comment by Aeyth8** [comment]
I managed to use stove a while ago
