### ISSUE TITLE
How can I fix these files not loading correctly? I can't edit anything like this :(

### ISSUE THREAD

**Issue by Peyton2017** [bananaturtlesandwich/stove#17]
![image_2024-03-18_062327298](https://github.com/bananaturtlesandwich/stove/assets/28621717/be2b01bc-382e-4e57-b8df-20ee61e70dbd)

**Comment by Peyton2017** [comment]
Hi, I've done this, and I still have the same issue. 
![image](https://github.com/bananaturtlesandwich/stove/assets/28621717/9e596130-b684-43f1-8dfd-77bcb261248b)

**Comment by Peyton2017** [comment]
> Hi, I've done this, and I still have the same issue. ![image](https://private-user-images.githubusercontent.com/28621717/314568731-9e596130-b684-43f1-8dfd-77bcb261248b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTAwMTIsIm5iZiI6MTcxMDk0OTcxMiwicGF0aCI6Ii8yODYyMTcxNy8zMTQ1Njg3MzEtOWU1OTYxMzAtYjY4NC00M2YxLThkZmQtNzdiY2IyNjEyNDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE1NDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMmI2ZDk4ODZhNjY3ZjFlZjI0NjRmMWZhNTg0ZTNiMjAwNDFkODcyZjM5OTMyODdiYzBkMWEzODJiZWZkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3uQXYhrPpVZqXPuoNV_KAqRGyfSo50ayQIVYFjl-jvo)

I know the AES key is correct, since applications like QuickBMS, UModel, and FModel all work using it.

**Comment by bananaturtlesandwich** [comment]
okay can you find an asset called SM_LCave_P_Meta in the pak?
