### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by acyc070** [bananaturtlesandwich/stove#19]
**Before you open an issue**
latest in releases
**Describe the bug**
even the window does not have time to fully appear and everything crashes
**To Reproduce**
Steps to reproduce the behaviour:
1. Open 'stove.exe'
2. crash
**Operating system**
Windows 7

**Comment by bananaturtlesandwich** [comment]
sorry don't have a windows 7 machine so can't really test - guessing this is to do with the backend which is here https://github.com/bevyengine/bevy

**Comment by acyc070** [comment]
use VMware workstation

**Comment by acyc070** [comment]
i updated to windows 10

**Comment by acyc070** [comment]
i think you need to refactor rendering engine to work with windows 7

**Comment by acyc070** [comment]
#23

**Comment by bananaturtlesandwich** [comment]
okay then that'll be on the issue you mentioned no need to reopen this one
