### ISSUE TITLE
Program crashes when loading large umaps

### ISSUE THREAD

**Issue by Auricrystal** [bananaturtlesandwich/stove#2]
Unsure what files are required for umaps to be read but included what i think is relevant.

When uncompressed this umap is about 73.6MB (5.5MB umap+ 69.8MB uexp).

I have compressed through .rar and then wrapped in .zip so that github allows the upload, i hope this causes no issue.
[PlayerBase.zip](https://github.com/bananaturtlesandwich/stove/files/10254982/PlayerBase.zip)

Crashes immediately upon pressing open, the file comes from a game between 4.19 and 4.22 in versioning and trying all of these lead to the same crash.

**Comment by bananaturtlesandwich** [comment]
From looking at it seems to be an assumption on the underlying api - I'd submit an issue over on this repository where the `unreal_asset` project is located: https://github.com/AstroTechies/unrealmodding/issues

**Comment by bananaturtlesandwich** [comment]
UAssetGUI seems to have the same problem when loading the asset:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/71292624/208383732-089ecdf8-e798-443d-ab06-0344944ea898.png">

**Comment by bananaturtlesandwich** [comment]
Just resolved this with a PR to unreal asset so next version should work
