### ISSUE TITLE
No 3D Models appearing just wireframe

### ISSUE THREAD

**Issue by GamerBoy563** [bananaturtlesandwich/stove#21]
No AES required for this game
![image](https://github.com/user-attachments/assets/2a6c3f9f-f8b1-4463-b999-2e540c3a0979)
![image](https://github.com/user-attachments/assets/423ac9de-f650-4ce0-8abf-3f2e0821d9da)
ive tried adding the paks folder and the extracted paks folder with no luck
![image](https://github.com/user-attachments/assets/8e13c120-ff6c-40f1-ab6b-66ca82887e76)

**Comment by bananaturtlesandwich** [comment]
ah looks like the map makes heavy use of lods which I need to account for - unfortunately won't be able to work on this for a couple weeks but will get to it then :)

**Comment by bananaturtlesandwich** [comment]
also got some other stuff in the works

**Comment by GamerBoy563** [comment]
Is there a fix for it in the meantime?

**Comment by bananaturtlesandwich** [comment]
no I physically don't have any sort of coding environment for the next couple weeks so am unable to work on this in any capacity

**Comment by GamerBoy563** [comment]
Yo yo I saw you commited like 5 mins ago did you fix the issue above or do you want me to test?

**Comment by bananaturtlesandwich** [comment]
i'm working through i think this exact same issue with another person so hopefully soon fixed :)

**Comment by GamerBoy563** [comment]
I added you on discord a while back so we could get instant responses to help out with figuring the issue so I can test stuff as I know how to build source code with visual studio

**Comment by GamerBoy563** [comment]
Any ETA on this issue?

**Comment by bananaturtlesandwich** [comment]
the other guy might have a different issue could you dm me on discord then?

**Comment by GamerBoy563** [comment]
spuds#5419 right?

**Comment by GamerBoy563** [comment]
![image](https://github.com/user-attachments/assets/274b0606-7621-4d04-b6ed-7293b44bb942)

**Comment by bananaturtlesandwich** [comment]
yup going to sleep now though

**Comment by GamerBoy563** [comment]
my discord is zen_364 if you wanna add me

**Comment by GamerBoy563** [comment]
can you accept my request

**Comment by bananaturtlesandwich** [comment]
fixed loading behaviour for content in plugins
