### ISSUE TITLE
When the new build will be?


### ISSUE THREAD

**Issue by acyc070** [bananaturtlesandwich/stove#24]

**Comment by bananaturtlesandwich** [comment]
i have some features i would really like to work at the moment but i should probably release what i have now

**Comment by bananaturtlesandwich** [comment]
released

**Comment by acyc070** [comment]
it's good and i recommend to setup autobuild process after committing

**Comment by bananaturtlesandwich** [comment]
there is an autobuild for releases because i can't build for linux and mac but it doesn't link oodle since that's a proprietary library so can't be distributed to the autobuild
