### ISSUE TITLE
Map Level UE 4.17 SAOFB Crash

### ISSUE THREAD

**Issue by LievreAI** [bananaturtlesandwich/stove#3]
i try to open 1 map using that tool and its simply crashed no log nothing

the game using aes key : h67GrjX2aGMgrAQeNwf9VmCYbt50ylJFeP3rIhbxh4e9bZXnqm8sbvEjWGOi6rgs
unreal engine version is : 4.17

**Comment by bananaturtlesandwich** [comment]
Could you please send the map? Otherwise I can't test myself. Also aes key paks aren't currently supported but that shouldn't cause a crash

**Comment by LievreAI** [comment]
got you i will upload it soon i at the work now to mega.co.nz

**Comment by LievreAI** [comment]
@bananaturtlesandwich 
sorry for the long time i was at vaction so this is the map
[https://mega.nz/file/oNhHRICT#P9YZw4UYd6FqoJ0bWIIqDuXRr73GQDiv7lQSpF2YtM0](url)

and its the same for all the maps

**Comment by bananaturtlesandwich** [comment]
works fine on [latest release](https://github.com/bananaturtlesandwich/stove/releases) - 0.5.0 had a major fix for large map files so I suspect that may have been your problem

**Comment by LievreAI** [comment]
@bananaturtlesandwich but why i cant really saw the map visual and not dots

**Comment by bananaturtlesandwich** [comment]
you have to add the game paks folder as a resource from the top left

**Comment by LievreAI** [comment]
@bananaturtlesandwich did it and crashed

**Comment by bananaturtlesandwich** [comment]
Oh yeah aes isn't supported by stove yet

**Comment by LievreAI** [comment]
do you plan to support it soon ?

**Comment by bananaturtlesandwich** [comment]
Oh yeah aes isn't supported by stove yet yep it's implemented just need to put in ui and storage for it

**Comment by LievreAI** [comment]
i belive then you 7 hours ago right ?
