### ISSUE TITLE
[Question] How do I duplicate an object?

### ISSUE THREAD

**Issue by Marold57** [bananaturtlesandwich/stove#31]
I'm trying to figure out how to duplicate something.

I select an object and press CTRL + C.
Stove tells me “Location copied” in the top right corner

If I now press CTRL + V Stove says “Location pasted”.
But the object is not duplicated and I am not sure if this is the right function to duplicate?

So what is this function for?

**Comment by Marold57** [comment]
Oh, I just saw that the shortcuts are listed in the help menu, I also found the shortcut for copying there and the object has been copied. Works now. Shortcut is: alt + left drag

Sorry !

**Comment by bananaturtlesandwich** [comment]
no worries!
