### ISSUE TITLE
include_header: true on headerless property

### ISSUE THREAD

**Issue by Andipog** [bananaturtlesandwich/stove#4]
It happens whenever I try to transplant any asset from one map to another

**Comment by bananaturtlesandwich** [comment]
Ok could you please send the map files? (umap and uexp if present)

**Comment by Andipog** [comment]
[GridMap.zip](https://github.com/bananaturtlesandwich/stove/files/10959753/GridMap.zip)
[City2.zip](https://github.com/bananaturtlesandwich/stove/files/10959757/City2.zip)


I tried transplanting things from City2 to GridMap, but I couldn't get it to work.

Apart from that other things in the program do work very well :)

**Comment by Andipog** [comment]
also should mention, it only happens if i save after the transplant. also corrupts the map if i try to reload the map (another error which ill try to send soon)

**Comment by bananaturtlesandwich** [comment]
Seems to be fine on latest version for me (although I don't know exactly what you're transplanting - I'm going to make an issue template so this isn't necessary in future)

**Comment by Andipog** [comment]
Hmm, strange.
I'll just redownload it and see

**Comment by Andipog** [comment]
I tried from one map to another and it works. Probably something to do with that map. Thanks for the help!

**Comment by bananaturtlesandwich** [comment]
no prob!
