### ISSUE TITLE
Select multiple things to transplant?

### ISSUE THREAD

**Issue by Tamashh** [bananaturtlesandwich/stove#5]
Is it possible to add a feature to select multiple things at once when transplanting?

**Comment by bananaturtlesandwich** [comment]
Ooh that's a really good idea I'll definitely look at doing that. I also need to think about multiple selection but multiple transplants is very doable atm

**Comment by Tamashh** [comment]
Multiple selection would be handy but I can manage without it but transplanting multiple things at once would be very useful.
Thanks for responding so quick btw

**Comment by bananaturtlesandwich** [comment]
implemented in cccb9ed :)
