### ISSUE TITLE
Models Don't seem to load. 

### ISSUE THREAD

**Issue by OmegasGithub** [bananaturtlesandwich/stove#6]
I've put the AES key in, as well as the pak folder. For whatever reason, stove does not appear to be able to find models, displaying the map only as green bounding boxes. This might be user error, so is there something I might be doing wrong? Thanks in advance.

**Comment by bananaturtlesandwich** [comment]
hmm...that's interesting it's probably not reading the paks properly - I'll add some error detection for pak reading for next release and we can have a look at the issue again then

**Comment by OmegasGithub** [comment]
Sounds good, appreciate it!

**Comment by Betaboycreatorgithub** [comment]
still isnt working

**Comment by bananaturtlesandwich** [comment]
> still isnt working

is there any messages now showing that can help fix the issue?

**Comment by Betaboycreatorgithub** [comment]
> > still isnt working
> 
> is there any messages now showing that can help fix the issue?

Not as far as i can tell. It just dosen't work. My issue isnt with models its with maps as well. I just dont see anything even though i gave stove the pak folder.

**Comment by Betaboycreatorgithub** [comment]
https://github.com/bananaturtlesandwich/stove/assets/116523251/6cf33408-52fd-4adb-a2d9-76c38e63608e

here is a video of the issue. please let me know if im just doing something wrong lol

**Comment by bananaturtlesandwich** [comment]
Yeah this a usage issue - you need to extract the .umap files from the pak and open those either from the file tab or ctrl o

**Comment by Betaboycreatorgithub** [comment]
> Yeah this a usage issue - you need to extract the .umap files from the pak and open those either from the file tab or ctrl o

I figured out how to use it. However, now this is what i see when opening a umap.
![Screenshot 2023-08-16 221345](https://github.com/bananaturtlesandwich/stove/assets/116523251/21f49c78-572c-43a2-be72-684406753836)

**Comment by bananaturtlesandwich** [comment]
Hmm...that's interesting - turn off cache meshes and see what happens

**Comment by Betaboycreatorgithub** [comment]
> Hmm...that's interesting - turn off cache meshes and see what happens

no difference.

**Comment by Betaboycreatorgithub** [comment]
> Hmm...that's interesting - turn off cache meshes and see what happens

the message its giving me is "failed to fill whole buffer"

**Comment by Betaboycreatorgithub** [comment]
its also saying no valid key provided even though i inputted the AES key.

**Comment by bananaturtlesandwich** [comment]
Okay is it saying where it's failing? What's the whole error message?

**Comment by Betaboycreatorgithub** [comment]
> Okay is it saying where it's failing? What's the whole error message?

its saying its failing at almost all the assets
lemme get the error message gimme a sec

**Comment by Betaboycreatorgithub** [comment]
> Okay is it saying where it's failing? What's the whole error message?

![Screenshot 2023-08-20 164143](https://github.com/bananaturtlesandwich/stove/assets/116523251/2f8c923d-f57d-45c9-ac5b-1962601fddc2)

**Comment by Betaboycreatorgithub** [comment]
also this
![Screenshot 2023-08-20 164222](https://github.com/bananaturtlesandwich/stove/assets/116523251/773a3c8d-4011-4ee5-ae01-44449577076b)

**Comment by bananaturtlesandwich** [comment]
are you still experiencing this on the new version?

**Comment by bananaturtlesandwich** [comment]
gonna have to close for inactivity if you don't respond
